### ISSUE TITLE
Hake

### ISSUE THREAD

**Issue by Arshdeep62** [aviator-predictor/aviator-predictor#13]
https://github.com/danielmiessler/SecLists/blob/refs%2Fheads%2Fmaster/Miscellaneous%2FEFF-Dice%2Flarge.txt

**Comment by Prince-classic** [comment]
I payed but not yet received anything

**Comment by ibbrahiim** [comment]
الي من دفعت ؟؟

في الأحد، ١٢ مايو ٢٠٢٤ ٣:٣٦ ص Prince-classic ***@***.***> كتب:

**Comment by Prince-classic** [comment]
Please write in English..

**Comment by Prince-classic** [comment]
Mr Ibrahim do you have the link you help me please

**Comment by ibbrahiim** [comment]
Who did you pay him?

[image: رمز "تم التحقق منها بواسطة المنتدى"]


في الجمعة، ١٧ مايو ٢٠٢٤ ١:٣١ ص Prince-classic ***@***.***>
كتب:

> Mr Ibrahim do you have the link you help me please
>

**Comment by Prince-classic** [comment]
To admin. In crypto
