### ISSUE TITLE
Hi I want 


### ISSUE THREAD

**Issue by Kicko098** [aviator-predictor/aviator-predictor#22]

**Comment by Prince-classic** [comment]
dont to make a deal with the owner of this .he is a scammer please

**Comment by Prince-classic** [comment]
> 

Don't buy he is a thief

**Comment by Kicko098** [comment]
Thanks for telling

**Comment by Prince-classic** [comment]
He is a big thief when you pay he will not reply you and he will block you

**Comment by Prince-classic** [comment]
Email me. Hamdun506@gmail.com
